[general]
import = [
    "~/.config/alacritty/themes/themes/gruber_darker.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
startup_mode = "Maximized"
dynamic_title = true
dynamic_padding = true
padding = { x = 0, y = 0 }
blur = false 
# opacity = 0.92

[font]
normal = {family = "Iosevka Nerd Font", style = "Regular"}
size = 15

[colors.primary]
# background = "#080808"

[colors]
cursor = { text = "#000000", cursor = "#ffffff" }

[selection]
save_to_clipboard = false

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Block", blinking= "Always"}
blink_interval = 550
