return {
    -- "xiyaowong/transparent.nvim",
    -- config = function()
    --     require("transparent").setup({
    --         enable = true,
    --         extra_groups = {
    --             "Normal",
    --             "NormalNC",
    --             "TelescopeBorder",
    --             "NvimTreeNormal",
    --             "LualineNormal",
    --         },
    --     })
    --     require("transparent").clear_prefix("NeoTree")
    --     -- require("transparent").clear_prefix("lualine")
    --     -- depends on pc, these settings are needed
    --     vim.cmd("highlight Normal guibg=NONE")
    --     vim.cmd("highlight Lualine guibg=#333333")
    --     vim.cmd("highlight Lualine guifg=#333333")
    --     vim.cmd("highlight NormalNC guibg=NONE")
    --     vim.cmd("highlight CursorLine guibg=NONE")
    --
    --     vim.keymap.set("n", "<leader>tr", ":TransparentToggle<CR>")
    --     vim.keymap.set("n", "<leader>td", ":TransparentDisable<CR>")
    -- end,
}
